version: '3.8'

services:
  db:
    image: postgres:15
    container_name: inventario_db
    restart: always
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: inventario_tienda
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: